# Site
repository: Asrlex/MyCV
favicon: images/favicon.ico

# Content configuration version
version: 2

# Theme settings
theme: jekyll-theme-cayman

# Personal info
name: Alejandro Sánchez Rodríguez
title: Software Engineer & Product Manager
email: alexsruc@hotmail.com
website: https://asrlex.github.io/MyCV/

# Dark Mode (true/false/never)
darkmode: false

# About Section
about_title: Sobre mí
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Soy una persona entusiasta, motivada y muy dedicada a mi entorno profesional. La experiencia trabajando en equipo desde el inicio de mi carrera profesional me ha ayudado a desarrollar una cultura de equipo enfocada en el progreso colaborativo de proyectos y tareas.

  Mis áreas de conocmiento principales son <mark>Node.js</mark>, <mark>Python</mark>, <mark>SQL</mark> y <mark>Java</mark>, con concimientos de Groovy y C. 

  Mi curiosidad me ayuda a mantener un aprendizaje constante. Tengo mucho interés por la tecnología en general y cómo evoluciona, principalmente en desarrollo e IA. La evolución de los principales modelos de IA desde un punto de vista de uso ético de la tecnología, para aprender a implementar estas soluciones de una manera segura para sus usuarios es un tema que encuentro muy relevante en el zeitgeist tecnológico.

  El aprendizaje también lo llevo a expandir mis conocimientos de desarrollo. Mediante cursos, tutoriales y revisión de documentación de otros proyectos, estoy aprendiendo sobre Bun, Docker, Kubernetes y React, como tecnologías complementarias a los entornos en los que trabajo. Bun, como alternativa muy plausible a Node, Docker y Kubernetes para el despliegue containerizado de aplicaciones, y React para mejorar el portfolio de tecnologías de front-end.

  Esta curiosidad también la desarrollo en el ámbito de los idiomas. Desde la infancia he estudiado inglés  hasta alcanzar el bilingüismo, con un título C1-ACE acreditado y nivel C2. En años más recientes he aprendido alemán, hasta alcanzar un nivel B2 con título B2-Mittelstufe. Además, he podido desenvolverme en entornos nativos de estas lenguas al haber vivido en Canadá y Alemania durante varios meses. Como complemento, tengo un título B1 de francés y estoy aprendiendo italiano de forma autodidacta.

content:
  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Servinform
        link: servinform.com
        # link_text: boringcompany.com
        sub_title: Responsable de Desarrollo y Reingeniería de Procesos 
        caption: Agosto 2022 - Presente
        description: | # this will include new lines to allow paragraphs
            Desde el equipo de BPM he trabajado en proyectos de reingeniería y transformación digital de procesos, buscando eficiencias y mejoras en la gestión de los mismos.

            Como <mark>responsable de desarrollo</mark>, he creado y liderado un equipo de desarrollo de software tanto para clientes como para uso interno de la propia empresa de forma transveral. Esto se ha logrado con:
              - Aplicaciones web con __Node.js, Express.js y React__.
              - Aplicaciones de escritorio con __Python__, basado en la librería __PyQt5 y tkinter__.
              - Automatización de tareas con __CPython y Python/Selenium__.
              - Gestión de bases de datos SQL con __SQLite, MySQL y SQL Server__.
            
            En el ámbito de <mark>reingeniería de procesos</mark>, he trabajado en proyectos para entidades financieras, aseguradoras y clientes en el campo de la salud.
              - __Auditoría de servicios__. Análisis de calidad de flujo de trabajo, calidad del dato producido y detección de ineficiencias.
              - Desarrollo de nuevos modelos de negocio según especificaciones del proyecto.
    
      - layout: left
        title: CSOIP
        sub_title: Desarrollador Junior / Control y Reporting 
        caption: Agosto 2017 - Agosto 2022
        description: | # this will include new lines to allow paragraphs
            En el equipo de Control y Reporting, he trabajado directamente para la dirección de la empresa en capacidad de desarrollador y analista de datos. Mis tareas principales han sido:
              - Desarrollo de aplicaciones web con __Node.js y Express.js__.
              - Desarrollo de aplicaciones de escritorio con __Java__.
              - Automatización de tareas con __CPython__.
              - Gestión de bases de datos SQL con __SQLite, MySQL y SQL Server__.
              - Cálculo de KPIs y SLAs para control y gestión de la productividad.
              - Manejo de Qlikview, PowerBI y paquete Office.

  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UPM
        sub_title: Ingeniería Telemática
        description: | # this will include new lines to allow paragraphs
          - Matrículas de Honor en múltiples asignaturas de prgramación.
          - Conocimiento avanzado en redes y sistemas.
          - Experiencia en desarrollo sobre Arduino y Raspberry Pi.
          - Monitorización de redes con Wireshark.
          - Conocimientos de seguridad informática.
          - Conocimiento de UML.

  - title: Idiomas # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Dominio de idiomas
        sub_title: "Idioma nativo: Español"
        description: | # this will include new lines to allow paragraphs
          |                                               | Comprensión auditiva  | Comprensión lectora | Producción oral | Interacción oral  | Expresión escrita |
          | --------------------------------------------- | :-----------------:   | :-----------------: | :-------------: | :---------------: | :---------------: |
          | **INGLÉS**   ![UK](./images/uk.png "UK")      | C2                    | C2                  | C2              | C2                | C2                |
          | **ALEMÁN**   ![GER](./images/german.png "GER")| B2                    | B2                  | B2              | B2                | B2                |
          | **FRANCÉS**  ![FRA](./images/italy.png "FRA") | B1                    | B1                  | B1              | B1                | B1                |
          | **ITALIANO** ![ITA](./images/france.png "ITA")| A2                    | A2                  | A2              | A2                | A2                |
        
          

  - title: Competencias de desarrollo # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Conocimientos
        sub_title: |
          Tecnologías, pilas de desarrollo y herramientas en las que tengo experiencia.

          _¿Qué sería de la vida, si no tuviéramos el valor de intentar algo nuevo? (Vincent Van Gogh)_
        description: | # this will include new lines to allow paragraphs
          
          - ![VS logo](./images/visual-studio.png "VS logo") ![Bash logo](./images/gnu-bash.png "Bash logo") **General**
            - Alta exigencia y disciplina documentando y estructurando código y proyectos.
            - Seguimiento de buenas prácticas y estilos.
            - Experiencia con IDEs y editores como **VSCode, Eclipse, IntelliJ y PyCharm**.
            - Experiencia gestionando proyectos en **OpenProject**.
            - Dominio de entorno **Linux** y **bash* para gestión de archivos, permisos y paquetes. 4 años de experiencia.


          - **WebDev Full-Stack**: 3 años de experiencia profesional full-stack.
            * ![Node logo](./images/node-js.png "Node logo") **Back-end:**
                - Dominio de **Node.js** y **express.js.**
                - Dominio de mecanismos de **autenticación y login**, tanto manuales como mediante Passport (y opcionalmente la gestión del almacenamiento de sesiones).
                - Integración con diferentes bases de datos (**SQLServer, MongoDB, SQLite, MySQL**), tanto manualmente como mediante ORM/ODMs (**Mongoose, Sequelize**).
                - Implementación de modelos de trabajo estandarizados con separación **View-Route-Controller**.
                - Gestión de ficheros con **multer**.
                - Implementación de mecanismos de seguridad como cifrado de datos (**bcrypt**), cabeceras de seguridad/CSP (**helmet**),
                - API de Excel mediante **exceljs**.
                - Gestión de **cookies** y **sesiones**.
            * ![Javascript logo](./images/js-file.png "Javascript logo") ![React logo](./images/physics.png "React logo") ![Bootstrap logo](./images/bootstrap.png "Bootstrap logo") **Front-end:**
                - Dominio de herramientas de templating como **Ejs** y **Pug**.
                - Dominio de **CSS** y **Sass**.
                - Integración de Sass con Node/Express.
                - Dominio de **Bootstrap 4.0-5.2**.
                - Dominio de **React** con **JSX**.


          - ![Python logo](./images/python.png "Python logo") **Python**: 4 años de experiencia profesional.
            - Automatización de tareas de gestión de ficheros, reporting y análisis de datos.
            - Desarrollo de **APIs REST** en **Flask** con **OpenAPI**.
            - Dominio de API de **Excel**.


          - ![sql logo](./images/sql-server.png "sql logo") **Bases de datos:** 7 años de experiencia profesional con DB relacionales (**MySQL, SQLServer y SQLite**) y 2 con no relacionales (**MongoDB**).
            - Triggers.
            - Limpieza y optimización de queries.
            - Batches.


          - ![Outsystems logo](./images/outsystems.png "Outsystems logo") **Low-code:** 1 año de experiencia trabajando con soluciones low-code.
            - Desarrollo de aplicaciones web y móviles con **Outsystems**.
              - Desarrollo full-stack funcional y visual.
            - Desarrollo de aplicaciones web con **ServiOps**.
              - Scripting con Groovy y Javascript.


          - ![Java logo](./images/java.png "Java logo") **Java:** 4 años de experiencia profesional.
            - Dominio de framework y filosofía de desarrollo **Spring MVC**.
            - Dominio de **Hibernate** como framework **ORM**.
            - Experiencia trabajando con patrón **MVC** con **Spring MVC** y **JavaFX**.
            - Dominio y uso muy extendido de **JDBC** con MySQL, SQLServer y MS Access.
            - Trabajo prolongado con **diferentes APIs de logging** (Logback, Log4j 2 y tinylog 2).
            - Desarrollo de aplicaciones **REST** con JAX-Jersey.
            - Desarrollador Java junior de aplicaciones desktop. Interfaces gráficas con **Swing** y **JavaFX**.
            - Dominio API **POI** de Excel.
            - Aplicaciones **multihilo** .


          - ![Git logo](./images/git.png "Git logo") ![Github logo](./images/github.png "Github logo") **Flow control.**
            - **Git y Github** para control de versiones.
            - **Jenkins** para CI/CD.


          - **Deployment**
            - Despliegues en **Microsoft Server**.
            - Despliegues en **Linux**.
            - Despliegues en **Docker**.
            - Despliegues desde Github a **Heroku** y **Firebase**.
            - Despliegues manuales en servidor propio (NAS, proyectos personales, etc.).


          - **Misc.**
            - **Conocimientos de Groovy**.
            - **Conocimientos de C**.
            - **Conocimientos de Selenium**.
          

          ---

      - layout: left
        title: Proyectos
        link: github.com/Asrlex
        # link_text: Project Website
        additional_links:
          - title:  Asrlex/MyCV
            icon: fab fa-github
            url: github.com/Asrlex/MyCV
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          
          ![Node logo](./images/node-js.png "Node logo") **Node**
            - **Herramientas de grabación** (**CLIENTE**)
              - Herramientas web de **grabación de datos** y **gestión documental** para clientes de renombre nacionales y europeos.
              - **API REST** con express.js
              - Front con **BS 5.2,** **Sass** y **Ejs**.
              - Login manual.
              - Integración con SQLite y **SQLServer**.
              - Desplegadas en servidor con **Microsoft Server**.
            - **Portal de empleados** (**RRHH**)
              - Webapp para agrupar y mostrar todos los recursos disponibles para los empleados de la empresa, y accesos a otras aplicaciones y utilidades, así como gestión de facturación de los departamentos.
              - **API REST** con express.js
              - Front con **BS 5.2,** **Sass** y **Ejs**.
              - Login manual.
              - Integración con SQLite y **SQLServer**.
              - Indexado de documentos en diferentes directorios y discos de red.
              - Desplegada en servidor con **Microsoft Server**.
            - **Gestión de pólizas** (**SEGUROS**)
              - Aplicación web para la gestión de pólizas de seguros y pensiones para cliente.
              - **API REST** con express.js.
              - Front con **React**, **BS 5.2**, **Sass** y **Ejs**.
              - Login manual.
              - Integración con **SQLServer**.
              - Interacción con **APIs de cliente**.
              - Despliegue en **Linux**.
            - **Travel Journal** (**PERSONAL**)
              - **Webapp** de journaling de viajes que permite añadir y gestionar destinos agrupados en viajes.
              - API REST con express.js.
              - Front con **BS 5.2**, **Sass** y **Ejs**.
              - Login manual o Google con **Passport**.
              - Integración con **MongoDB**.
              - Gestión de **hosting de imágenes con Cloudinary**.
              - **Geolocalización** mediante **MapBox API** para visualización y agrupación de marcadores.
              - Despliegue inicial en **Heroku** desde Github y transferido a Firebase.
              ![Landing](./images/trjournal1.png "Landing")
              ![Resources](./images/trjournal2.png "Resources")

          ![Java logo](./images/java.png "Java logo") **Java**
            - **Agenda de operaciones** (**BANCA**)
              - Aplicación de escritorio para agendar, asignar y gestionar operaciones enviadas en Excel por gestorías.
              - GUI con **Java Swing**.
              - JDBC a **SQL Server**.
              - Identificación automática con usuario corporativo.
            - **Control de moratorias** (**BANCA**)
              - Aplicación de escritorio para controlar operaciones de moratorias post-covid.
              - GUI con **JavaFX**.
              - JDBC a **SQL Server**.
              - Identificación automática con usuario corporativo.
            - **Control de vacaciones y ausencias** (**RRHH**)
              - Herramienta de escritorio para controlar las vacaciones de todos los empleados de la empresa y la aprobación de solicitudes por los responsables. Control de ausencias por parte de responsables y RRHH, y gestión de los justificantes y motivos.
              - GUI con **JavaFX**.
              - Integración de calendarios y datepickers personalizados.
              - Integración con **SQL Server**.
              - **API Outlook** (pre-OAuth) para envío de correos de aprobación y confirmación.
              - Identificación automática con usuario corporativo.
            - **Tracker** (**PERSONAL**)
              - Herramienta de escritorio para controlar progreso en diferentes proyectos o videojuegos a partir de una serie de parámetros iniciales.
              - GUI con **JavaFX**.
              - JDBC a **MySQL**.
              - Identificación manual.

            ![Python logo](./images/python.png "Python logo") **Python** 
            - **Renombramiento de archivos** (**CLIENTE**)
              - Script que, a partir de un maestro en Excel, renombra una serie de archivos de un directorio concreto y los encarpeta según los filtros especificados.
              - CLI.
              - API Excel.
              - Bundled en .exe
            - **Web-scraper** (**CLIENTE**)
              - Script que, a partir de una serie de parámetros, descarga ficheros de la página web corporativa correspondiente a una oficina del cliente.
              - CLI.
              - API Selenium.
              - Ajustes de seguridad para evitar bloqueos.
              - Parametrizado con .ini.
              - Bundled en .exe.
            - **Generador de aplicaciones** (**USO INTERNO**)
              - Script que, a partir de una serie de parámetros genera una base de datos, formulario y serie de reglas de flujo de trabajo.
              - Los parámetros se pueden proporcionar por CLI, fichero .ini o Excel.
              - Busca resolver pequeñas necesidades de grabación de datos.
              - Genera base de datos relacional ligera SQLite. Aparte de los campos, permite definir restricciones para estos.
              - Genera un formulario basado en labels e inputs básicos con pygui (texto, dropdowns, checkboxes, botones...).

            ![Outsystems logo](./images/outsystems.png "Outsystems logo") **Outsystems Low-Code** 
            - **Gestión de casos** (**CLIENTE**)
              - Aplicación web para la gestión de casos de bastanteos y reclamaciones.
              - Desarrollo full-stack funcional y visual.
              - Procesamiento de carga y descarga de ficheros Excel.
              - Desarrollo de flujos de negocio mediante acciones de cliente y servidor.
            
            ![Groovy logo](./images/groovy.png "Groovy logo") **Groovy**
            - **Scripting** (**USO INTERNO**)
              - Script que, procesando parámetros, genera una serie de documentos y ficheros de configuración para la generación de aplicaciones con ServiOps.
              - Script que filtran y reconocen el tipo de persona asociada a un NIF español proporcionado a la entrada de datos en ServiOps.
              - Script que conecta ServiOps con la API del repositorio interno de usuarios de la empresa para crear usuarios automáticamente en cuanto se registre su alta.

          
          ---

      - layout: top-middle
        title: Formación
        quote: >
          ¿Qué sería de la vida, si no tuviéramos el valor de intentar algo nuevo? (Vincent Van Gogh)
        description: | # this will include new lines to allow paragraphs
          - **Python**
            - Certificación oficial de Python by PUE.
          - **Git y Github**
            - Formación online para profundizar en control de versiones.
          - **Docker y Kubernetes**
            - Formación online para profundizar en despliegue de aplicaciones.
          - **React**
            - Formación online para profundizar en desarrollo front-end.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
